### ISSUE TITLE
vue前端开发中，如何配置axios和element-plus

### ISSUE THREAD

**Issue by lizhengyang2023** [BUAA-Soft-2023-Summer/Soft-Summer-2023#8]
**开发框架：Vue**
**问题**
你好，我通过npm安装了axios和element-plus，以及 unplugin-vue-components 和 unplugin- auto-import后，在配置过程中出现了问题，请问如何正确配置element-plus？

在命令提示符运行npm run dev之后，出现了如下报错：
> failed to load config from C:\Users\lilin\todoList\vite.config.js
error when starting dev server:
TypeError: (0 , import_resolvers.default) is not a function
    at Object.<anonymous> (C:\Users\lilin\todoList\vite.config.js:48:34)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at _require.extensions.<computed> [as .js] (file:///C:/Users/lilin/todoList/node_modules/vite/dist/node/chunks/dep-df561101.js:66253:24)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadConfigFromBundledFile (file:///C:/Users/lilin/todoList/node_modules/vite/dist/node/chunks/dep-df561101.js:66261:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadConfigFromFile (file:///C:/Users/lilin/todoList/node_modules/vite/dist/node/chunks/dep-df561101.js:66086:28)`

我的vite.config.js代码如下：
`import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})`
@LLLeoLi

**Comment by lizhengyang2023** [comment]
查了一下element 的官网，已经解决了
